title: Binary
cgitLink: https://github.com/nomeata/gipeda/commit/
# logLink: https://raw.githubusercontent.com/nomeata/ghc-speed-logs/master/{{rev}}.log
limitRecent: 20
start: 4853c7b467409468ac9029558c8ed3caa4a4be6c

benchmarks:
  - match: "throughput/*"
    smallerIsBetter: False
    unit: MB/s
    group: "Throughput measurements"
